package by.home.les11.controller;

public enum CommandName {

	GO_TO_MAIN_PAGE, SHOW_ALL_STUDENTS, SHOW_ALL_SUBJECTS, SHOW_ALL, SHOW_ALL_ABOUT_STUDENT, ADD_NEW_STUDENT,
	ADD_NEW_SUBJECT, GO_TO_UPDATE_STUDENT, UPDATE_STUDENT, DELETE_STUDENT, GO_TO_UPDATE_SUBJECT, UPDATE_SUBJECT, DELETE_SUBJECT, 
	ALL_STUDENT_ON_THE_SUBJECT, GO_TO_ADD_MARK, ADD_MARK
}
